import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const chauPhilomeneOneRegular = localFont({
  src: "../fonts/ChauPhilomeneOne-Regular.ttf",
  variable: "--font-chau-philomene-one",
});

const reuscoDisplay = localFont({
  src: "../fonts/Reusco-Display.otf",
  variable: "--font-reusco-display",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Image Text Editor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${chauPhilomeneOneRegular.variable} ${reuscoDisplay.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
